# Generated by Django 4.2.11 on 2024-03-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaterial",
            name="quantity_type",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="remainder_type",
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remainder",
            field=models.IntegerField(),
        ),
    ]
