# Generated by Django 4.2.11 on 2024-03-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_remove_productmaterial_quantity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="quantity_type",
            field=models.CharField(
                choices=[("MT", "Meter"), ("MTSQ", "Meter Square"), ("PC", "Piece")],
                default="PC",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="productmaterial",
            name="quantity",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
