# Generated by Django 4.2.11 on 2024-03-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_productmaterial_quantity_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmaterial",
            name="material_id",
        ),
        migrations.RemoveField(
            model_name="productmaterial",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="material_id",
        ),
        migrations.AddField(
            model_name="productmaterial",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="warehouse.material",
            ),
        ),
        migrations.AddField(
            model_name="productmaterial",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material",
                to="warehouse.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warehouse",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warehouse",
                to="warehouse.material",
            ),
        ),
    ]
